#Requires AutoHotkey v2.0
#Warn All, Off

; === TotalCommander.Maps: keymaps + action comments ===
; owner: TotalCommander.ahk (same-dir include chain)
TotalCommander_Keymaps(engine) {
    ; 检测 TC 路径
    DetectTCPath()

    ; 修复 64 位控件 ID
    FixTCEditId()


    ; 中文注释表 (517 条, 抽自原版 vim.Comment, 供 g 提示面板显示; 后续特化注册可覆盖措辞)
    engine.SetAction("<cm_100Percent>", T("act.TotalCommander.cm_100Percent"))
    engine.SetAction("<cm_50Percent>", T("act.TotalCommander.cm_50Percent"))
    engine.SetAction("<cm_About>", T("act.TotalCommander.cm_About"))
    engine.SetAction("<cm_AddPathToCmdline>", T("act.TotalCommander.cm_AddPathToCmdline"))
    engine.SetAction("<cm_AdministerServer>", T("act.TotalCommander.cm_AdministerServer"))
    engine.SetAction("<cm_Associate>", T("act.TotalCommander.cm_Associate"))
    engine.SetAction("<cm_ButtonConfig>", T("act.TotalCommander.cm_ButtonConfig"))
    engine.SetAction("<cm_CDtree>", T("act.TotalCommander.cm_CDtree"))
    engine.SetAction("<cm_ChangeStartMenu>", T("act.TotalCommander.cm_ChangeStartMenu"))
    engine.SetAction("<cm_ClearAll>", T("act.TotalCommander.cm_ClearAll"))
    engine.SetAction("<cm_ClearAllCfg>", T("act.TotalCommander.cm_ClearAllCfg"))
    engine.SetAction("<cm_ClearAllFiles>", T("act.TotalCommander.cm_ClearAllFiles"))
    engine.SetAction("<cm_ClearAllFolders>", T("act.TotalCommander.cm_ClearAllFolders"))
    engine.SetAction("<cm_ClearCmdLine>", T("act.TotalCommander.cm_ClearCmdLine"))
    engine.SetAction("<cm_ClearFiles>", T("act.TotalCommander.cm_ClearFiles"))
    engine.SetAction("<cm_ClearFolders>", T("act.TotalCommander.cm_ClearFolders"))
    engine.SetAction("<cm_ClearSelCfg>", T("act.TotalCommander.cm_ClearSelCfg"))
    engine.SetAction("<cm_CloseAllTabs>", T("act.TotalCommander.cm_CloseAllTabs"))
    engine.SetAction("<cm_CloseCurrentTab>", T("act.TotalCommander.cm_CloseCurrentTab"))
    engine.SetAction("<cm_ColorConfig>", T("act.TotalCommander.cm_ColorConfig"))
    engine.SetAction("<cm_Combine>", T("act.TotalCommander.cm_Combine"))
    engine.SetAction("<cm_CommandBrowser>", T("act.TotalCommander.cm_CommandBrowser"))
    engine.SetAction("<cm_CompareDirs>", T("act.TotalCommander.cm_CompareDirs"))
    engine.SetAction("<cm_CompareDirsWithSubdirs>", T("act.TotalCommander.cm_CompareDirsWithSubdirs"))
    engine.SetAction("<cm_CompareFilesByContent>", T("act.TotalCommander.cm_CompareFilesByContent"))
    engine.SetAction("<cm_Config>", T("act.TotalCommander.cm_Config"))
    engine.SetAction("<cm_Config2>", T("act.TotalCommander.cm_Config2"))
    engine.SetAction("<cm_ConfigChangeIniFiles>", T("act.TotalCommander.cm_ConfigChangeIniFiles"))
    engine.SetAction("<cm_ConfigSaveDirHistory>", T("act.TotalCommander.cm_ConfigSaveDirHistory"))
    engine.SetAction("<cm_ConfigSavePos>", T("act.TotalCommander.cm_ConfigSavePos"))
    engine.SetAction("<cm_ConfigSaveSettings>", T("act.TotalCommander.cm_ConfigSaveSettings"))
    engine.SetAction("<cm_Confirmation>", T("act.TotalCommander.cm_Confirmation"))
    engine.SetAction("<cm_ConfTabChange>", T("act.TotalCommander.cm_ConfTabChange"))
    engine.SetAction("<cm_ContentStopLoadFields>", T("act.TotalCommander.cm_ContentStopLoadFields"))
    engine.SetAction("<cm_ContextMenu>", T("act.TotalCommander.cm_ContextMenu"))
    engine.SetAction("<cm_ContextMenuInternal>", T("act.TotalCommander.cm_ContextMenuInternal"))
    engine.SetAction("<cm_ContextMenuInternalCursor>", T("act.TotalCommander.cm_ContextMenuInternalCursor"))
    engine.SetAction("<cm_Copy>", T("act.TotalCommander.cm_Copy"))
    engine.SetAction("<cm_CopyConfig>", T("act.TotalCommander.cm_CopyConfig"))
    engine.SetAction("<cm_CopyFileDetailsToClip>", T("act.TotalCommander.cm_CopyFileDetailsToClip"))
    engine.SetAction("<cm_CopyFpFileDetailsToClip>", T("act.TotalCommander.cm_CopyFpFileDetailsToClip"))
    engine.SetAction("<cm_CopyFullNamesToClip>", T("act.TotalCommander.cm_CopyFullNamesToClip"))
    engine.SetAction("<cm_CopyNamesToClip>", T("act.TotalCommander.cm_CopyNamesToClip"))
    engine.SetAction("<cm_CopyNetFileDetailsToClip>", T("act.TotalCommander.cm_CopyNetFileDetailsToClip"))
    engine.SetAction("<cm_CopyNetNamesToClip>", T("act.TotalCommander.cm_CopyNetNamesToClip"))
    engine.SetAction("<cm_CopyOtherpanel>", T("act.TotalCommander.cm_CopyOtherpanel"))
    engine.SetAction("<cm_CopySamepanel>", T("act.TotalCommander.cm_CopySamepanel"))
    engine.SetAction("<cm_CopySrcPathToClip>", T("act.TotalCommander.cm_CopySrcPathToClip"))
    engine.SetAction("<cm_CopyToClipboard>", T("act.TotalCommander.cm_CopyToClipboard"))
    engine.SetAction("<cm_CopyTrgPathToClip>", T("act.TotalCommander.cm_CopyTrgPathToClip"))
    engine.SetAction("<cm_CountDirContent>", T("act.TotalCommander.cm_CountDirContent"))
    engine.SetAction("<cm_CRCcheck>", T("act.TotalCommander.cm_CRCcheck"))
    engine.SetAction("<cm_CRCcreate>", T("act.TotalCommander.cm_CRCcreate"))
    engine.SetAction("<cm_CreateShortcut>", T("act.TotalCommander.cm_CreateShortcut"))
    engine.SetAction("<cm_CustomColumnConfig>", T("act.TotalCommander.cm_CustomColumnConfig"))
    engine.SetAction("<cm_CustomColumnDlg>", T("act.TotalCommander.cm_CustomColumnDlg"))
    engine.SetAction("<cm_CutToClipboard>", T("act.TotalCommander.cm_CutToClipboard"))
    engine.SetAction("<cm_Decode>", T("act.TotalCommander.cm_Decode"))
    engine.SetAction("<cm_Delete>", T("act.TotalCommander.cm_Delete"))
    engine.SetAction("<cm_DirBranch>", T("act.TotalCommander.cm_DirBranch"))
    engine.SetAction("<cm_DirBranchSel>", T("act.TotalCommander.cm_DirBranchSel"))
    engine.SetAction("<cm_DirectCableConnect>", T("act.TotalCommander.cm_DirectCableConnect"))
    engine.SetAction("<cm_DirectoryHistory>", T("act.TotalCommander.cm_DirectoryHistory"))
    engine.SetAction("<cm_DirectoryHotlist>", T("act.TotalCommander.cm_DirectoryHotlist"))
    engine.SetAction("<cm_DirMatch>", T("act.TotalCommander.cm_DirMatch"))
    engine.SetAction("<cm_DirTabsConfig>", T("act.TotalCommander.cm_DirTabsConfig"))
    engine.SetAction("<cm_DirTabsShowMenu>", T("act.TotalCommander.cm_DirTabsShowMenu"))
    engine.SetAction("<cm_DisplayConfig>", T("act.TotalCommander.cm_DisplayConfig"))
    engine.SetAction("<cm_Edit>", T("act.TotalCommander.cm_Edit"))
    engine.SetAction("<cm_EditAuditInfo>", T("act.TotalCommander.cm_EditAuditInfo"))
    engine.SetAction("<cm_EditComment>", T("act.TotalCommander.cm_EditComment"))
    engine.SetAction("<cm_EditConfig>", T("act.TotalCommander.cm_EditConfig"))
    engine.SetAction("<cm_EditOwnerInfo>", T("act.TotalCommander.cm_EditOwnerInfo"))
    engine.SetAction("<cm_EditPath>", T("act.TotalCommander.cm_EditPath"))
    engine.SetAction("<cm_EditPermissionInfo>", T("act.TotalCommander.cm_EditPermissionInfo"))
    engine.SetAction("<cm_Encode>", T("act.TotalCommander.cm_Encode"))
    engine.SetAction("<cm_Exchange>", T("act.TotalCommander.cm_Exchange"))
    engine.SetAction("<cm_ExchangeSelBoth>", T("act.TotalCommander.cm_ExchangeSelBoth"))
    engine.SetAction("<cm_ExchangeSelection>", T("act.TotalCommander.cm_ExchangeSelection"))
    engine.SetAction("<cm_ExchangeSelFiles>", T("act.TotalCommander.cm_ExchangeSelFiles"))
    engine.SetAction("<cm_ExchangeSelFolders>", T("act.TotalCommander.cm_ExchangeSelFolders"))
    engine.SetAction("<cm_ExchangeWithTabs>", T("act.TotalCommander.cm_ExchangeWithTabs"))
    engine.SetAction("<cm_ExecuteDOS>", T("act.TotalCommander.cm_ExecuteDOS"))
    engine.SetAction("<cm_Exit>", T("act.TotalCommander.cm_Exit"))
    engine.SetAction("<cm_FileSync>", T("act.TotalCommander.cm_FileSync"))
    engine.SetAction("<cm_FocusButtonBar>", T("act.TotalCommander.cm_FocusButtonBar"))
    engine.SetAction("<cm_FocusCmdLine>", T("act.TotalCommander.cm_FocusCmdLine"))
    engine.SetAction("<cm_FocusLeft>", T("act.TotalCommander.cm_FocusLeft"))
    engine.SetAction("<cm_FocusRight>", T("act.TotalCommander.cm_FocusRight"))
    engine.SetAction("<cm_FocusSrc>", T("act.TotalCommander.cm_FocusSrc"))
    engine.SetAction("<cm_FocusTrg>", T("act.TotalCommander.cm_FocusTrg"))
    engine.SetAction("<cm_FontConfig>", T("act.TotalCommander.cm_FontConfig"))
    engine.SetAction("<cm_FtpAbort>", T("act.TotalCommander.cm_FtpAbort"))
    engine.SetAction("<cm_FtpAddToList>", T("act.TotalCommander.cm_FtpAddToList"))
    engine.SetAction("<cm_FtpConfig>", T("act.TotalCommander.cm_FtpConfig"))
    engine.SetAction("<cm_FtpConnect>", T("act.TotalCommander.cm_FtpConnect"))
    engine.SetAction("<cm_FtpDisconnect>", T("act.TotalCommander.cm_FtpDisconnect"))
    engine.SetAction("<cm_FtpDownloadList>", T("act.TotalCommander.cm_FtpDownloadList"))
    engine.SetAction("<cm_FtpHiddenFiles>", T("act.TotalCommander.cm_FtpHiddenFiles"))
    engine.SetAction("<cm_FtpNew>", T("act.TotalCommander.cm_FtpNew"))
    engine.SetAction("<cm_FtpResumeDownload>", T("act.TotalCommander.cm_FtpResumeDownload"))
    engine.SetAction("<cm_FtpSelectTransferMode>", T("act.TotalCommander.cm_FtpSelectTransferMode"))
    engine.SetAction("<cm_GetFileSpace>", T("act.TotalCommander.cm_GetFileSpace"))
    engine.SetAction("<cm_GoToDir>", T("act.TotalCommander.cm_GoToDir"))
    engine.SetAction("<cm_GotoDriveA>", T("act.TotalCommander.cm_GotoDriveA"))
    engine.SetAction("<cm_GotoDriveC>", T("act.TotalCommander.cm_GotoDriveC"))
    engine.SetAction("<cm_GotoDriveD>", T("act.TotalCommander.cm_GotoDriveD"))
    engine.SetAction("<cm_GotoDriveE>", T("act.TotalCommander.cm_GotoDriveE"))
    engine.SetAction("<cm_GotoDriveF>", T("act.TotalCommander.cm_GotoDriveF"))
    engine.SetAction("<cm_GotoDriveZ>", T("act.TotalCommander.cm_GotoDriveZ"))
    engine.SetAction("<cm_GoToFirstEntry>", T("act.TotalCommander.cm_GoToFirstEntry"))
    engine.SetAction("<cm_GoToFirstFile>", T("act.TotalCommander.cm_GoToFirstFile"))
    engine.SetAction("<cm_GoToLockedDir>", T("act.TotalCommander.cm_GoToLockedDir"))
    engine.SetAction("<cm_GotoNextDir>", T("act.TotalCommander.cm_GotoNextDir"))
    engine.SetAction("<cm_GotoNextDrive>", T("act.TotalCommander.cm_GotoNextDrive"))
    engine.SetAction("<cm_GotoNextLocalDir>", T("act.TotalCommander.cm_GotoNextLocalDir"))
    engine.SetAction("<cm_GotoNextSelected>", T("act.TotalCommander.cm_GotoNextSelected"))
    engine.SetAction("<cm_GoToParent>", T("act.TotalCommander.cm_GoToParent"))
    engine.SetAction("<cm_GotoPreviousDir>", T("act.TotalCommander.cm_GotoPreviousDir"))
    engine.SetAction("<cm_GotoPreviousDrive>", T("act.TotalCommander.cm_GotoPreviousDrive"))
    engine.SetAction("<cm_GotoPreviousLocalDir>", T("act.TotalCommander.cm_GotoPreviousLocalDir"))
    engine.SetAction("<cm_GotoPrevSelected>", T("act.TotalCommander.cm_GotoPrevSelected"))
    engine.SetAction("<cm_GoToRoot>", T("act.TotalCommander.cm_GoToRoot"))
    engine.SetAction("<cm_HelpIndex>", T("act.TotalCommander.cm_HelpIndex"))
    engine.SetAction("<cm_IconConfig>", T("act.TotalCommander.cm_IconConfig"))
    engine.SetAction("<cm_IgnoreConfig>", T("act.TotalCommander.cm_IgnoreConfig"))
    engine.SetAction("<cm_IntCompareFilesByContent>", T("act.TotalCommander.cm_IntCompareFilesByContent"))
    engine.SetAction("<cm_InternalAssociate>", T("act.TotalCommander.cm_InternalAssociate"))
    engine.SetAction("<cm_Keyboard>", T("act.TotalCommander.cm_Keyboard"))
    engine.SetAction("<cm_LanguageConfig>", T("act.TotalCommander.cm_LanguageConfig"))
    engine.SetAction("<cm_LeftActivateTab1>", T("act.TotalCommander.cm_LeftActivateTab1"))
    engine.SetAction("<cm_LeftActivateTab10>", T("act.TotalCommander.cm_LeftActivateTab10"))
    engine.SetAction("<cm_LeftActivateTab2>", T("act.TotalCommander.cm_LeftActivateTab2"))
    engine.SetAction("<cm_LeftActivateTab3>", T("act.TotalCommander.cm_LeftActivateTab3"))
    engine.SetAction("<cm_LeftActivateTab4>", T("act.TotalCommander.cm_LeftActivateTab4"))
    engine.SetAction("<cm_LeftActivateTab5>", T("act.TotalCommander.cm_LeftActivateTab5"))
    engine.SetAction("<cm_LeftActivateTab6>", T("act.TotalCommander.cm_LeftActivateTab6"))
    engine.SetAction("<cm_LeftActivateTab7>", T("act.TotalCommander.cm_LeftActivateTab7"))
    engine.SetAction("<cm_LeftActivateTab8>", T("act.TotalCommander.cm_LeftActivateTab8"))
    engine.SetAction("<cm_LeftActivateTab9>", T("act.TotalCommander.cm_LeftActivateTab9"))
    engine.SetAction("<cm_LeftAllFiles>", T("act.TotalCommander.cm_LeftAllFiles"))
    engine.SetAction("<cm_LeftByDateTime>", T("act.TotalCommander.cm_LeftByDateTime"))
    engine.SetAction("<cm_LeftByExt>", T("act.TotalCommander.cm_LeftByExt"))
    engine.SetAction("<cm_LeftByName>", T("act.TotalCommander.cm_LeftByName"))
    engine.SetAction("<cm_LeftBySize>", T("act.TotalCommander.cm_LeftBySize"))
    engine.SetAction("<cm_LeftComments>", T("act.TotalCommander.cm_LeftComments"))
    engine.SetAction("<cm_LeftCustomView1>", T("act.TotalCommander.cm_LeftCustomView1"))
    engine.SetAction("<cm_LeftCustomView10>", T("act.TotalCommander.cm_LeftCustomView10"))
    engine.SetAction("<cm_LeftCustomView2>", T("act.TotalCommander.cm_LeftCustomView2"))
    engine.SetAction("<cm_LeftCustomView3>", T("act.TotalCommander.cm_LeftCustomView3"))
    engine.SetAction("<cm_LeftCustomView4>", T("act.TotalCommander.cm_LeftCustomView4"))
    engine.SetAction("<cm_LeftCustomView5>", T("act.TotalCommander.cm_LeftCustomView5"))
    engine.SetAction("<cm_LeftCustomView6>", T("act.TotalCommander.cm_LeftCustomView6"))
    engine.SetAction("<cm_LeftCustomView7>", T("act.TotalCommander.cm_LeftCustomView7"))
    engine.SetAction("<cm_LeftCustomView8>", T("act.TotalCommander.cm_LeftCustomView8"))
    engine.SetAction("<cm_LeftCustomView9>", T("act.TotalCommander.cm_LeftCustomView9"))
    engine.SetAction("<cm_LeftCustomViewMenu>", T("act.TotalCommander.cm_LeftCustomViewMenu"))
    engine.SetAction("<cm_LeftDirBranch>", T("act.TotalCommander.cm_LeftDirBranch"))
    engine.SetAction("<cm_LeftDirBranchSel>", T("act.TotalCommander.cm_LeftDirBranchSel"))
    engine.SetAction("<cm_LeftExecs>", T("act.TotalCommander.cm_LeftExecs"))
    engine.SetAction("<cm_LeftHideQuickview>", T("act.TotalCommander.cm_LeftHideQuickview"))
    engine.SetAction("<cm_LeftLong>", T("act.TotalCommander.cm_LeftLong"))
    engine.SetAction("<cm_LeftNegOrder>", T("act.TotalCommander.cm_LeftNegOrder"))
    engine.SetAction("<cm_LeftNextCustomView>", T("act.TotalCommander.cm_LeftNextCustomView"))
    engine.SetAction("<cm_LeftOpenDrives>", T("act.TotalCommander.cm_LeftOpenDrives"))
    engine.SetAction("<cm_LeftPathFocus>", T("act.TotalCommander.cm_LeftPathFocus"))
    engine.SetAction("<cm_LeftPrevCustomView>", T("act.TotalCommander.cm_LeftPrevCustomView"))
    engine.SetAction("<cm_LeftQuickInternalOnly>", T("act.TotalCommander.cm_LeftQuickInternalOnly"))
    engine.SetAction("<cm_LeftQuickview>", T("act.TotalCommander.cm_LeftQuickview"))
    engine.SetAction("<cm_LeftShort>", T("act.TotalCommander.cm_LeftShort"))
    engine.SetAction("<cm_LeftSortByCol1>", T("act.TotalCommander.cm_LeftSortByCol1"))
    engine.SetAction("<cm_LeftSortByCol10>", T("act.TotalCommander.cm_LeftSortByCol10"))
    engine.SetAction("<cm_LeftSortByCol2>", T("act.TotalCommander.cm_LeftSortByCol2"))
    engine.SetAction("<cm_LeftSortByCol3>", T("act.TotalCommander.cm_LeftSortByCol3"))
    engine.SetAction("<cm_LeftSortByCol4>", T("act.TotalCommander.cm_LeftSortByCol4"))
    engine.SetAction("<cm_LeftSortByCol5>", T("act.TotalCommander.cm_LeftSortByCol5"))
    engine.SetAction("<cm_LeftSortByCol6>", T("act.TotalCommander.cm_LeftSortByCol6"))
    engine.SetAction("<cm_LeftSortByCol7>", T("act.TotalCommander.cm_LeftSortByCol7"))
    engine.SetAction("<cm_LeftSortByCol8>", T("act.TotalCommander.cm_LeftSortByCol8"))
    engine.SetAction("<cm_LeftSortByCol9>", T("act.TotalCommander.cm_LeftSortByCol9"))
    engine.SetAction("<cm_LeftThumbs>", T("act.TotalCommander.cm_LeftThumbs"))
    engine.SetAction("<cm_LeftTree>", T("act.TotalCommander.cm_LeftTree"))
    engine.SetAction("<cm_LeftUnsorted>", T("act.TotalCommander.cm_LeftUnsorted"))
    engine.SetAction("<cm_LeftUserDef>", T("act.TotalCommander.cm_LeftUserDef"))
    engine.SetAction("<cm_LeftUserSpec>", T("act.TotalCommander.cm_LeftUserSpec"))
    engine.SetAction("<cm_List>", T("act.TotalCommander.cm_List"))
    engine.SetAction("<cm_ListInternalOnly>", T("act.TotalCommander.cm_ListInternalOnly"))
    engine.SetAction("<cm_LoadAllOnDemandFields>", T("act.TotalCommander.cm_LoadAllOnDemandFields"))
    engine.SetAction("<cm_LoadSelectionFromClip>", T("act.TotalCommander.cm_LoadSelectionFromClip"))
    engine.SetAction("<cm_LoadSelectionFromFile>", T("act.TotalCommander.cm_LoadSelectionFromFile"))
    engine.SetAction("<cm_LoadSelOnDemandFields>", T("act.TotalCommander.cm_LoadSelOnDemandFields"))
    engine.SetAction("<cm_LogConfig>", T("act.TotalCommander.cm_LogConfig"))
    engine.SetAction("<cm_MatchSrc>", T("act.TotalCommander.cm_MatchSrc"))
    engine.SetAction("<cm_Maximize>", T("act.TotalCommander.cm_Maximize"))
    engine.SetAction("<cm_Minimize>", T("act.TotalCommander.cm_Minimize"))
    engine.SetAction("<cm_MkDir>", T("act.TotalCommander.cm_MkDir"))
    engine.SetAction("<cm_MoveOnly>", T("act.TotalCommander.cm_MoveOnly"))
    engine.SetAction("<cm_MultiRenameFiles>", T("act.TotalCommander.cm_MultiRenameFiles"))
    engine.SetAction("<cm_NetConnect>", T("act.TotalCommander.cm_NetConnect"))
    engine.SetAction("<cm_NetDisconnect>", T("act.TotalCommander.cm_NetDisconnect"))
    engine.SetAction("<cm_NetShareDir>", T("act.TotalCommander.cm_NetShareDir"))
    engine.SetAction("<cm_NetUnshareDir>", T("act.TotalCommander.cm_NetUnshareDir"))
    engine.SetAction("<cm_NextCommand>", T("act.TotalCommander.cm_NextCommand"))
    engine.SetAction("<cm_NTinstallDriver>", T("act.TotalCommander.cm_NTinstallDriver"))
    engine.SetAction("<cm_NTremoveDriver>", T("act.TotalCommander.cm_NTremoveDriver"))
    engine.SetAction("<cm_OpenAsUser>", T("act.TotalCommander.cm_OpenAsUser"))
    engine.SetAction("<cm_OpenControls>", T("act.TotalCommander.cm_OpenControls"))
    engine.SetAction("<cm_OpenDesktop>", T("act.TotalCommander.cm_OpenDesktop"))
    engine.SetAction("<cm_OpenDirInNewTab>", T("act.TotalCommander.cm_OpenDirInNewTab"))
    engine.SetAction("<cm_OpenDirInNewTabOther>", T("act.TotalCommander.cm_OpenDirInNewTabOther"))
    engine.SetAction("<cm_OpenDrives>", T("act.TotalCommander.cm_OpenDrives"))
    engine.SetAction("<cm_OpenFonts>", T("act.TotalCommander.cm_OpenFonts"))
    engine.SetAction("<cm_OpenNetwork>", T("act.TotalCommander.cm_OpenNetwork"))
    engine.SetAction("<cm_OpenNewTab>", T("act.TotalCommander.cm_OpenNewTab"))
    engine.SetAction("<cm_OpenNewTabBg>", T("act.TotalCommander.cm_OpenNewTabBg"))
    engine.SetAction("<cm_OpenPrinters>", T("act.TotalCommander.cm_OpenPrinters"))
    engine.SetAction("<cm_OpenRecycled>", T("act.TotalCommander.cm_OpenRecycled"))
    engine.SetAction("<cm_OpenTransferManager>", T("act.TotalCommander.cm_OpenTransferManager"))
    engine.SetAction("<cm_PackerConfig>", T("act.TotalCommander.cm_PackerConfig"))
    engine.SetAction("<cm_PackFiles>", T("act.TotalCommander.cm_PackFiles"))
    engine.SetAction("<cm_PasteFromClipboard>", T("act.TotalCommander.cm_PasteFromClipboard"))
    engine.SetAction("<cm_PluginsConfig>", T("act.TotalCommander.cm_PluginsConfig"))
    engine.SetAction("<cm_PrevCommand>", T("act.TotalCommander.cm_PrevCommand"))
    engine.SetAction("<cm_PrintDir>", T("act.TotalCommander.cm_PrintDir"))
    engine.SetAction("<cm_PrintDirSub>", T("act.TotalCommander.cm_PrintDirSub"))
    engine.SetAction("<cm_PrintFile>", T("act.TotalCommander.cm_PrintFile"))
    engine.SetAction("<cm_Properties>", T("act.TotalCommander.cm_Properties"))
    engine.SetAction("<cm_QuickSearchConfig>", T("act.TotalCommander.cm_QuickSearchConfig"))
    engine.SetAction("<cm_RefreshConfig>", T("act.TotalCommander.cm_RefreshConfig"))
    engine.SetAction("<cm_Register>", T("act.TotalCommander.cm_Register"))
    engine.SetAction("<cm_ReloadSelThumbs>", T("act.TotalCommander.cm_ReloadSelThumbs"))
    engine.SetAction("<cm_RenameOnly>", T("act.TotalCommander.cm_RenameOnly"))
    engine.SetAction("<cm_RenameSingleFile>", T("act.TotalCommander.cm_RenameSingleFile"))
    engine.SetAction("<cm_RenMov>", T("act.TotalCommander.cm_RenMov"))
    engine.SetAction("<cm_RereadSource>", T("act.TotalCommander.cm_RereadSource"))
    engine.SetAction("<cm_Restore>", T("act.TotalCommander.cm_Restore"))
    engine.SetAction("<cm_RestoreSelection>", T("act.TotalCommander.cm_RestoreSelection"))
    engine.SetAction("<cm_Return>", T("act.TotalCommander.cm_Return"))
    engine.SetAction("<cm_RightActivateTab1>", T("act.TotalCommander.cm_RightActivateTab1"))
    engine.SetAction("<cm_RightActivateTab10>", T("act.TotalCommander.cm_RightActivateTab10"))
    engine.SetAction("<cm_RightActivateTab2>", T("act.TotalCommander.cm_RightActivateTab2"))
    engine.SetAction("<cm_RightActivateTab3>", T("act.TotalCommander.cm_RightActivateTab3"))
    engine.SetAction("<cm_RightActivateTab4>", T("act.TotalCommander.cm_RightActivateTab4"))
    engine.SetAction("<cm_RightActivateTab5>", T("act.TotalCommander.cm_RightActivateTab5"))
    engine.SetAction("<cm_RightActivateTab6>", T("act.TotalCommander.cm_RightActivateTab6"))
    engine.SetAction("<cm_RightActivateTab7>", T("act.TotalCommander.cm_RightActivateTab7"))
    engine.SetAction("<cm_RightActivateTab8>", T("act.TotalCommander.cm_RightActivateTab8"))
    engine.SetAction("<cm_RightActivateTab9>", T("act.TotalCommander.cm_RightActivateTab9"))
    engine.SetAction("<cm_RightAllFile>", T("act.TotalCommander.cm_RightAllFile"))
    engine.SetAction("<cm_RightByDateTim>", T("act.TotalCommander.cm_RightByDateTim"))
    engine.SetAction("<cm_RightByEx>", T("act.TotalCommander.cm_RightByEx"))
    engine.SetAction("<cm_RightByNam>", T("act.TotalCommander.cm_RightByNam"))
    engine.SetAction("<cm_RightBySiz>", T("act.TotalCommander.cm_RightBySiz"))
    engine.SetAction("<cm_RightComments>", T("act.TotalCommander.cm_RightComments"))
    engine.SetAction("<cm_RightCustomView1>", T("act.TotalCommander.cm_RightCustomView1"))
    engine.SetAction("<cm_RightCustomView10>", T("act.TotalCommander.cm_RightCustomView10"))
    engine.SetAction("<cm_RightCustomView2>", T("act.TotalCommander.cm_RightCustomView2"))
    engine.SetAction("<cm_RightCustomView3>", T("act.TotalCommander.cm_RightCustomView3"))
    engine.SetAction("<cm_RightCustomView4>", T("act.TotalCommander.cm_RightCustomView4"))
    engine.SetAction("<cm_RightCustomView5>", T("act.TotalCommander.cm_RightCustomView5"))
    engine.SetAction("<cm_RightCustomView6>", T("act.TotalCommander.cm_RightCustomView6"))
    engine.SetAction("<cm_RightCustomView7>", T("act.TotalCommander.cm_RightCustomView7"))
    engine.SetAction("<cm_RightCustomView8>", T("act.TotalCommander.cm_RightCustomView8"))
    engine.SetAction("<cm_RightCustomView9>", T("act.TotalCommander.cm_RightCustomView9"))
    engine.SetAction("<cm_RightCustomViewMen>", T("act.TotalCommander.cm_RightCustomViewMen"))
    engine.SetAction("<cm_RightDirBranch>", T("act.TotalCommander.cm_RightDirBranch"))
    engine.SetAction("<cm_RightDirBranchSel>", T("act.TotalCommander.cm_RightDirBranchSel"))
    engine.SetAction("<cm_RightExec>", T("act.TotalCommander.cm_RightExec"))
    engine.SetAction("<cm_RightHideQuickvie>", T("act.TotalCommander.cm_RightHideQuickvie"))
    engine.SetAction("<cm_RightLong>", T("act.TotalCommander.cm_RightLong"))
    engine.SetAction("<cm_RightNegOrde>", T("act.TotalCommander.cm_RightNegOrde"))
    engine.SetAction("<cm_RightNextCustomView>", T("act.TotalCommander.cm_RightNextCustomView"))
    engine.SetAction("<cm_RightOpenDrives>", T("act.TotalCommander.cm_RightOpenDrives"))
    engine.SetAction("<cm_RightPathFocu>", T("act.TotalCommander.cm_RightPathFocu"))
    engine.SetAction("<cm_RightPrevCustomView>", T("act.TotalCommander.cm_RightPrevCustomView"))
    engine.SetAction("<cm_RightQuickInternalOnl>", T("act.TotalCommander.cm_RightQuickInternalOnl"))
    engine.SetAction("<cm_RightQuickvie>", T("act.TotalCommander.cm_RightQuickvie"))
    engine.SetAction("<cm_RightShort>", T("act.TotalCommander.cm_RightShort"))
    engine.SetAction("<cm_RightSortByCol1>", T("act.TotalCommander.cm_RightSortByCol1"))
    engine.SetAction("<cm_RightSortByCol10>", T("act.TotalCommander.cm_RightSortByCol10"))
    engine.SetAction("<cm_RightSortByCol2>", T("act.TotalCommander.cm_RightSortByCol2"))
    engine.SetAction("<cm_RightSortByCol3>", T("act.TotalCommander.cm_RightSortByCol3"))
    engine.SetAction("<cm_RightSortByCol4>", T("act.TotalCommander.cm_RightSortByCol4"))
    engine.SetAction("<cm_RightSortByCol5>", T("act.TotalCommander.cm_RightSortByCol5"))
    engine.SetAction("<cm_RightSortByCol6>", T("act.TotalCommander.cm_RightSortByCol6"))
    engine.SetAction("<cm_RightSortByCol7>", T("act.TotalCommander.cm_RightSortByCol7"))
    engine.SetAction("<cm_RightSortByCol8>", T("act.TotalCommander.cm_RightSortByCol8"))
    engine.SetAction("<cm_RightSortByCol9>", T("act.TotalCommander.cm_RightSortByCol9"))
    engine.SetAction("<cm_RightThumb>", T("act.TotalCommander.cm_RightThumb"))
    engine.SetAction("<cm_RightTree>", T("act.TotalCommander.cm_RightTree"))
    engine.SetAction("<cm_RightUnsorte>", T("act.TotalCommander.cm_RightUnsorte"))
    engine.SetAction("<cm_RightUserDe>", T("act.TotalCommander.cm_RightUserDe"))
    engine.SetAction("<cm_RightUserSpe>", T("act.TotalCommander.cm_RightUserSpe"))
    engine.SetAction("<cm_SaveDetailsToFile>", T("act.TotalCommander.cm_SaveDetailsToFile"))
    engine.SetAction("<cm_SaveDetailsToFileA>", T("act.TotalCommander.cm_SaveDetailsToFileA"))
    engine.SetAction("<cm_SaveDetailsToFileW>", T("act.TotalCommander.cm_SaveDetailsToFileW"))
    engine.SetAction("<cm_SaveSelection>", T("act.TotalCommander.cm_SaveSelection"))
    engine.SetAction("<cm_SaveSelectionToFile>", T("act.TotalCommander.cm_SaveSelectionToFile"))
    engine.SetAction("<cm_SaveSelectionToFileA>", T("act.TotalCommander.cm_SaveSelectionToFileA"))
    engine.SetAction("<cm_SaveSelectionToFileW>", T("act.TotalCommander.cm_SaveSelectionToFileW"))
    engine.SetAction("<cm_SearchFor>", T("act.TotalCommander.cm_SearchFor"))
    engine.SetAction("<cm_SearchStandalone>", T("act.TotalCommander.cm_SearchStandalone"))
    engine.SetAction("<cm_SelectAll>", T("act.TotalCommander.cm_SelectAll"))
    engine.SetAction("<cm_SelectAllBoth>", T("act.TotalCommander.cm_SelectAllBoth"))
    engine.SetAction("<cm_SelectAllFiles>", T("act.TotalCommander.cm_SelectAllFiles"))
    engine.SetAction("<cm_SelectAllFolders>", T("act.TotalCommander.cm_SelectAllFolders"))
    engine.SetAction("<cm_SelectBoth>", T("act.TotalCommander.cm_SelectBoth"))
    engine.SetAction("<cm_SelectCurrentExtension>", T("act.TotalCommander.cm_SelectCurrentExtension"))
    engine.SetAction("<cm_SelectCurrentName>", T("act.TotalCommander.cm_SelectCurrentName"))
    engine.SetAction("<cm_SelectCurrentNameExt>", T("act.TotalCommander.cm_SelectCurrentNameExt"))
    engine.SetAction("<cm_SelectCurrentPath>", T("act.TotalCommander.cm_SelectCurrentPath"))
    engine.SetAction("<cm_SelectFiles>", T("act.TotalCommander.cm_SelectFiles"))
    engine.SetAction("<cm_SelectFolders>", T("act.TotalCommander.cm_SelectFolders"))
    engine.SetAction("<cm_SeparateTree1>", T("act.TotalCommander.cm_SeparateTree1"))
    engine.SetAction("<cm_SeparateTree2>", T("act.TotalCommander.cm_SeparateTree2"))
    engine.SetAction("<cm_SeparateTreeOff>", T("act.TotalCommander.cm_SeparateTreeOff"))
    engine.SetAction("<cm_SetAttrib>", T("act.TotalCommander.cm_SetAttrib"))
    engine.SetAction("<cm_ShowFileUser>", T("act.TotalCommander.cm_ShowFileUser"))
    engine.SetAction("<cm_ShowHint>", T("act.TotalCommander.cm_ShowHint"))
    engine.SetAction("<cm_ShowOnlySelected>", T("act.TotalCommander.cm_ShowOnlySelected"))
    engine.SetAction("<cm_ShowQuickSearch>", T("act.TotalCommander.cm_ShowQuickSearch"))
    engine.SetAction("<cm_ShowRemoteMenu>", T("act.TotalCommander.cm_ShowRemoteMenu"))
    engine.SetAction("<cm_ShrinkSelection>", T("act.TotalCommander.cm_ShrinkSelection"))
    engine.SetAction("<cm_Split>", T("act.TotalCommander.cm_Split"))
    engine.SetAction("<cm_SpreadSelection>", T("act.TotalCommander.cm_SpreadSelection"))
    engine.SetAction("<cm_SrcActivateTab1>", T("act.TotalCommander.cm_SrcActivateTab1"))
    engine.SetAction("<cm_SrcActivateTab10>", T("act.TotalCommander.cm_SrcActivateTab10"))
    engine.SetAction("<cm_SrcActivateTab2>", T("act.TotalCommander.cm_SrcActivateTab2"))
    engine.SetAction("<cm_SrcActivateTab3>", T("act.TotalCommander.cm_SrcActivateTab3"))
    engine.SetAction("<cm_SrcActivateTab4>", T("act.TotalCommander.cm_SrcActivateTab4"))
    engine.SetAction("<cm_SrcActivateTab5>", T("act.TotalCommander.cm_SrcActivateTab5"))
    engine.SetAction("<cm_SrcActivateTab6>", T("act.TotalCommander.cm_SrcActivateTab6"))
    engine.SetAction("<cm_SrcActivateTab7>", T("act.TotalCommander.cm_SrcActivateTab7"))
    engine.SetAction("<cm_SrcActivateTab8>", T("act.TotalCommander.cm_SrcActivateTab8"))
    engine.SetAction("<cm_SrcActivateTab9>", T("act.TotalCommander.cm_SrcActivateTab9"))
    engine.SetAction("<cm_SrcAllFiles>", T("act.TotalCommander.cm_SrcAllFiles"))
    engine.SetAction("<cm_SrcByDateTime>", T("act.TotalCommander.cm_SrcByDateTime"))
    engine.SetAction("<cm_SrcByExt>", T("act.TotalCommander.cm_SrcByExt"))
    engine.SetAction("<cm_SrcByName>", T("act.TotalCommander.cm_SrcByName"))
    engine.SetAction("<cm_SrcBySize>", T("act.TotalCommander.cm_SrcBySize"))
    engine.SetAction("<cm_SrcComments>", T("act.TotalCommander.cm_SrcComments"))
    engine.SetAction("<cm_SrcCustomView1>", T("act.TotalCommander.cm_SrcCustomView1"))
    engine.SetAction("<cm_SrcCustomView10>", T("act.TotalCommander.cm_SrcCustomView10"))
    engine.SetAction("<cm_SrcCustomView2>", T("act.TotalCommander.cm_SrcCustomView2"))
    engine.SetAction("<cm_SrcCustomView3>", T("act.TotalCommander.cm_SrcCustomView3"))
    engine.SetAction("<cm_SrcCustomView4>", T("act.TotalCommander.cm_SrcCustomView4"))
    engine.SetAction("<cm_SrcCustomView5>", T("act.TotalCommander.cm_SrcCustomView5"))
    engine.SetAction("<cm_SrcCustomView6>", T("act.TotalCommander.cm_SrcCustomView6"))
    engine.SetAction("<cm_SrcCustomView7>", T("act.TotalCommander.cm_SrcCustomView7"))
    engine.SetAction("<cm_SrcCustomView8>", T("act.TotalCommander.cm_SrcCustomView8"))
    engine.SetAction("<cm_SrcCustomView9>", T("act.TotalCommander.cm_SrcCustomView9"))
    engine.SetAction("<cm_SrcCustomViewMenu>", T("act.TotalCommander.cm_SrcCustomViewMenu"))
    engine.SetAction("<cm_SrcExecs>", T("act.TotalCommander.cm_SrcExecs"))
    engine.SetAction("<cm_SrcHideQuickview>", T("act.TotalCommander.cm_SrcHideQuickview"))
    engine.SetAction("<cm_SrcLong>", T("act.TotalCommander.cm_SrcLong"))
    engine.SetAction("<cm_SrcNegOrder>", T("act.TotalCommander.cm_SrcNegOrder"))
    engine.SetAction("<cm_SrcNextCustomView>", T("act.TotalCommander.cm_SrcNextCustomView"))
    engine.SetAction("<cm_SrcOpenDrives>", T("act.TotalCommander.cm_SrcOpenDrives"))
    engine.SetAction("<cm_SrcPathFocus>", T("act.TotalCommander.cm_SrcPathFocus"))
    engine.SetAction("<cm_SrcPrevCustomView>", T("act.TotalCommander.cm_SrcPrevCustomView"))
    engine.SetAction("<cm_SrcQuickInternalOnly>", T("act.TotalCommander.cm_SrcQuickInternalOnly"))
    engine.SetAction("<cm_SrcQuickview>", T("act.TotalCommander.cm_SrcQuickview"))
    engine.SetAction("<cm_SrcShort>", T("act.TotalCommander.cm_SrcShort"))
    engine.SetAction("<cm_SrcSortByCol1>", T("act.TotalCommander.cm_SrcSortByCol1"))
    engine.SetAction("<cm_SrcSortByCol10>", T("act.TotalCommander.cm_SrcSortByCol10"))
    engine.SetAction("<cm_SrcSortByCol2>", T("act.TotalCommander.cm_SrcSortByCol2"))
    engine.SetAction("<cm_SrcSortByCol3>", T("act.TotalCommander.cm_SrcSortByCol3"))
    engine.SetAction("<cm_SrcSortByCol4>", T("act.TotalCommander.cm_SrcSortByCol4"))
    engine.SetAction("<cm_SrcSortByCol5>", T("act.TotalCommander.cm_SrcSortByCol5"))
    engine.SetAction("<cm_SrcSortByCol6>", T("act.TotalCommander.cm_SrcSortByCol6"))
    engine.SetAction("<cm_SrcSortByCol7>", T("act.TotalCommander.cm_SrcSortByCol7"))
    engine.SetAction("<cm_SrcSortByCol8>", T("act.TotalCommander.cm_SrcSortByCol8"))
    engine.SetAction("<cm_SrcSortByCol9>", T("act.TotalCommander.cm_SrcSortByCol9"))
    engine.SetAction("<cm_SrcThumbs>", T("act.TotalCommander.cm_SrcThumbs"))
    engine.SetAction("<cm_SrcTree>", T("act.TotalCommander.cm_SrcTree"))
    engine.SetAction("<cm_SrcUnsorted>", T("act.TotalCommander.cm_SrcUnsorted"))
    engine.SetAction("<cm_SrcUserDef>", T("act.TotalCommander.cm_SrcUserDef"))
    engine.SetAction("<cm_SrcUserSpec>", T("act.TotalCommander.cm_SrcUserSpec"))
    engine.SetAction("<cm_Switch83Names>", T("act.TotalCommander.cm_Switch83Names"))
    engine.SetAction("<cm_SwitchDirSort>", T("act.TotalCommander.cm_SwitchDirSort"))
    engine.SetAction("<cm_SwitchHidSys>", T("act.TotalCommander.cm_SwitchHidSys"))
    engine.SetAction("<cm_SwitchIgnoreList>", T("act.TotalCommander.cm_SwitchIgnoreList"))
    engine.SetAction("<cm_SwitchLongNames>", T("act.TotalCommander.cm_SwitchLongNames"))
    engine.SetAction("<cm_SwitchOverlayIcons>", T("act.TotalCommander.cm_SwitchOverlayIcons"))
    engine.SetAction("<cm_SwitchSeparateTree>", T("act.TotalCommander.cm_SwitchSeparateTree"))
    engine.SetAction("<cm_SwitchToNextTab>", T("act.TotalCommander.cm_SwitchToNextTab"))
    engine.SetAction("<cm_SwitchToPreviousTab>", T("act.TotalCommander.cm_SwitchToPreviousTab"))
    engine.SetAction("<cm_SwitchWatchDirs>", T("act.TotalCommander.cm_SwitchWatchDirs"))
    engine.SetAction("<cm_SwitchX64Redirection>", T("act.TotalCommander.cm_SwitchX64Redirection"))
    engine.SetAction("<cm_SyncChangeDir>", T("act.TotalCommander.cm_SyncChangeDir"))
    engine.SetAction("<cm_SysInfo>", T("act.TotalCommander.cm_SysInfo"))
    engine.SetAction("<cm_TestArchive>", T("act.TotalCommander.cm_TestArchive"))
    engine.SetAction("<cm_ThumbnailsConfig>", T("act.TotalCommander.cm_ThumbnailsConfig"))
    engine.SetAction("<cm_ToggleLockCurrentTab>", T("act.TotalCommander.cm_ToggleLockCurrentTab"))
    engine.SetAction("<cm_ToggleLockDcaCurrentTab>", T("act.TotalCommander.cm_ToggleLockDcaCurrentTab"))
    engine.SetAction("<cm_ToggleSeparateTree1>", T("act.TotalCommander.cm_ToggleSeparateTree1"))
    engine.SetAction("<cm_ToggleSeparateTree2>", T("act.TotalCommander.cm_ToggleSeparateTree2"))
    engine.SetAction("<cm_TransferLeft>", T("act.TotalCommander.cm_TransferLeft"))
    engine.SetAction("<cm_TransferRight>", T("act.TotalCommander.cm_TransferRight"))
    engine.SetAction("<cm_TrgActivateTab1>", T("act.TotalCommander.cm_TrgActivateTab1"))
    engine.SetAction("<cm_TrgActivateTab10>", T("act.TotalCommander.cm_TrgActivateTab10"))
    engine.SetAction("<cm_TrgActivateTab2>", T("act.TotalCommander.cm_TrgActivateTab2"))
    engine.SetAction("<cm_TrgActivateTab3>", T("act.TotalCommander.cm_TrgActivateTab3"))
    engine.SetAction("<cm_TrgActivateTab4>", T("act.TotalCommander.cm_TrgActivateTab4"))
    engine.SetAction("<cm_TrgActivateTab5>", T("act.TotalCommander.cm_TrgActivateTab5"))
    engine.SetAction("<cm_TrgActivateTab6>", T("act.TotalCommander.cm_TrgActivateTab6"))
    engine.SetAction("<cm_TrgActivateTab7>", T("act.TotalCommander.cm_TrgActivateTab7"))
    engine.SetAction("<cm_TrgActivateTab8>", T("act.TotalCommander.cm_TrgActivateTab8"))
    engine.SetAction("<cm_TrgActivateTab9>", T("act.TotalCommander.cm_TrgActivateTab9"))
    engine.SetAction("<cm_TrgNextCustomView>", T("act.TotalCommander.cm_TrgNextCustomView"))
    engine.SetAction("<cm_TrgPrevCustomView>", T("act.TotalCommander.cm_TrgPrevCustomView"))
    engine.SetAction("<cm_TrgSortByCol1>", T("act.TotalCommander.cm_TrgSortByCol1"))
    engine.SetAction("<cm_TrgSortByCol10>", T("act.TotalCommander.cm_TrgSortByCol10"))
    engine.SetAction("<cm_TrgSortByCol2>", T("act.TotalCommander.cm_TrgSortByCol2"))
    engine.SetAction("<cm_TrgSortByCol3>", T("act.TotalCommander.cm_TrgSortByCol3"))
    engine.SetAction("<cm_TrgSortByCol4>", T("act.TotalCommander.cm_TrgSortByCol4"))
    engine.SetAction("<cm_TrgSortByCol5>", T("act.TotalCommander.cm_TrgSortByCol5"))
    engine.SetAction("<cm_TrgSortByCol6>", T("act.TotalCommander.cm_TrgSortByCol6"))
    engine.SetAction("<cm_TrgSortByCol7>", T("act.TotalCommander.cm_TrgSortByCol7"))
    engine.SetAction("<cm_TrgSortByCol8>", T("act.TotalCommander.cm_TrgSortByCol8"))
    engine.SetAction("<cm_TrgSortByCol9>", T("act.TotalCommander.cm_TrgSortByCol9"))
    engine.SetAction("<cm_UnloadPlugins>", T("act.TotalCommander.cm_UnloadPlugins"))
    engine.SetAction("<cm_UnpackFiles>", T("act.TotalCommander.cm_UnpackFiles"))
    engine.SetAction("<cm_UnselectCurrentExtension>", T("act.TotalCommander.cm_UnselectCurrentExtension"))
    engine.SetAction("<cm_UnselectCurrentName>", T("act.TotalCommander.cm_UnselectCurrentName"))
    engine.SetAction("<cm_UnselectCurrentNameExt>", T("act.TotalCommander.cm_UnselectCurrentNameExt"))
    engine.SetAction("<cm_UnselectCurrentPath>", T("act.TotalCommander.cm_UnselectCurrentPath"))
    engine.SetAction("<cm_UserMenu1>", T("act.TotalCommander.cm_UserMenu1"))
    engine.SetAction("<cm_UserMenu10>", T("act.TotalCommander.cm_UserMenu10"))
    engine.SetAction("<cm_UserMenu2>", T("act.TotalCommander.cm_UserMenu2"))
    engine.SetAction("<cm_UserMenu3>", T("act.TotalCommander.cm_UserMenu3"))
    engine.SetAction("<cm_UserMenu4>", T("act.TotalCommander.cm_UserMenu4"))
    engine.SetAction("<cm_UserMenu5>", T("act.TotalCommander.cm_UserMenu5"))
    engine.SetAction("<cm_UserMenu6>", T("act.TotalCommander.cm_UserMenu6"))
    engine.SetAction("<cm_UserMenu7>", T("act.TotalCommander.cm_UserMenu7"))
    engine.SetAction("<cm_UserMenu8>", T("act.TotalCommander.cm_UserMenu8"))
    engine.SetAction("<cm_UserMenu9>", T("act.TotalCommander.cm_UserMenu9"))
    engine.SetAction("<cm_VersionInfo>", T("act.TotalCommander.cm_VersionInfo"))
    engine.SetAction("<cm_VerticalPanels>", T("act.TotalCommander.cm_VerticalPanels"))
    engine.SetAction("<cm_VisBreadCrumbs>", T("act.TotalCommander.cm_VisBreadCrumbs"))
    engine.SetAction("<cm_VisButtonbar>", T("act.TotalCommander.cm_VisButtonbar"))
    engine.SetAction("<cm_VisCmdLine>", T("act.TotalCommander.cm_VisCmdLine"))
    engine.SetAction("<cm_VisCurDir>", T("act.TotalCommander.cm_VisCurDir"))
    engine.SetAction("<cm_VisDirTabs>", T("act.TotalCommander.cm_VisDirTabs"))
    engine.SetAction("<cm_VisDriveButtons>", T("act.TotalCommander.cm_VisDriveButtons"))
    engine.SetAction("<cm_VisDriveCombo>", T("act.TotalCommander.cm_VisDriveCombo"))
    engine.SetAction("<cm_VisFlatDriveButtons>", T("act.TotalCommander.cm_VisFlatDriveButtons"))
    engine.SetAction("<cm_VisFlatInterface>", T("act.TotalCommander.cm_VisFlatInterface"))
    engine.SetAction("<cm_VisHistHotButtons>", T("act.TotalCommander.cm_VisHistHotButtons"))
    engine.SetAction("<cm_VisitHomepage>", T("act.TotalCommander.cm_VisitHomepage"))
    engine.SetAction("<cm_VisKeyButtons>", T("act.TotalCommander.cm_VisKeyButtons"))
    engine.SetAction("<cm_VisStatusbar>", T("act.TotalCommander.cm_VisStatusbar"))
    engine.SetAction("<cm_VisTabHeader>", T("act.TotalCommander.cm_VisTabHeader"))
    engine.SetAction("<cm_VisTwoDriveButtons>", T("act.TotalCommander.cm_VisTwoDriveButtons"))
    engine.SetAction("<cm_VisXPThemeBackground>", T("act.TotalCommander.cm_VisXPThemeBackground"))
    engine.SetAction("<cm_VolumeId>", T("act.TotalCommander.cm_VolumeId"))
    engine.SetAction("<cm_ZipPackerConfig>", T("act.TotalCommander.cm_ZipPackerConfig"))
    engine.SetAction("<TC_AlwayOnTop>", T("act.TotalCommander.TC_AlwayOnTop"))
    engine.SetAction("<TC_azHistory>", T("act.TotalCommander.TC_azHistory"))
    engine.SetAction("<TC_ClearTitle>", T("act.TotalCommander.TC_ClearTitle"))
    engine.SetAction("<TC_CopyDirectoryHotlist>", T("act.TotalCommander.TC_CopyDirectoryHotlist"))
    engine.SetAction("<TC_CopyFileContents>", T("act.TotalCommander.TC_CopyFileContents"))
    engine.SetAction("<TC_CopyNameOnly>", T("act.TotalCommander.TC_CopyNameOnly"))
    engine.SetAction("<TC_CopyUseQueues>", T("act.TotalCommander.TC_CopyUseQueues"))
    engine.SetAction("<TC_CreateBlankFile>", T("act.TotalCommander.TC_CreateBlankFile"))
    engine.SetAction("<TC_CreateBlankFileNoExt>", T("act.TotalCommander.TC_CreateBlankFileNoExt"))
    engine.SetAction("<TC_CreateFileShortcut>", T("act.TotalCommander.TC_CreateFileShortcut"))
    engine.SetAction("<TC_CreateFileShortcutToDesktop>", T("act.TotalCommander.TC_CreateFileShortcutToDesktop"))
    engine.SetAction("<TC_CreateFileShortcutToStartup>", T("act.TotalCommander.TC_CreateFileShortcutToStartup"))
    engine.SetAction("<TC_CreateNewFile>", T("act.TotalCommander.TC_CreateNewFile"))
    engine.SetAction("<TC_DownSelect>", T("act.TotalCommander.TC_DownSelect"))
    engine.SetAction("<TC_FileCopyForBak>", T("act.TotalCommander.TC_FileCopyForBak"))
    engine.SetAction("<TC_FileMoveForBak>", T("act.TotalCommander.TC_FileMoveForBak"))
    engine.SetAction("<TC_FilterSearchFNsuffix_exe>", T("act.TotalCommander.TC_FilterSearchFNsuffix_exe"))
    engine.SetAction("<TC_FocusTCCmd>", T("act.TotalCommander.TC_FocusTCCmd"))
    engine.SetAction("<TC_ForceDelete>", T("act.TotalCommander.TC_ForceDelete"))
    engine.SetAction("<TC_GoLastTab>", T("act.TotalCommander.TC_GoLastTab"))
    engine.SetAction("<TC_GotoLine>", T("act.TotalCommander.TC_GotoLine"))
    engine.SetAction("<TC_GotoNextDirOther>", T("act.TotalCommander.TC_GotoNextDirOther"))
    engine.SetAction("<TC_GoToParentEx>", T("act.TotalCommander.TC_GoToParentEx"))
    engine.SetAction("<TC_GotoPreviousDirOther>", T("act.TotalCommander.TC_GotoPreviousDirOther"))
    engine.SetAction("<TC_Half>", T("act.TotalCommander.TC_Half"))
    engine.SetAction("<TC_InsertMode>", T("act.TotalCommander.TC_InsertMode"))
    engine.SetAction("<TC_LastLine>", T("act.TotalCommander.TC_LastLine"))
    engine.SetAction("<TC_ListMark>", T("act.TotalCommander.TC_ListMark"))
    engine.SetAction("<TC_Mark>", T("act.TotalCommander.TC_Mark"))
    engine.SetAction("<TC_MarkFile>", T("act.TotalCommander.TC_MarkFile"))
    engine.SetAction("<TC_MoveAllFilesToPrevFolder>", T("act.TotalCommander.TC_MoveAllFilesToPrevFolder"))
    engine.SetAction("<TC_MoveDirectoryHotlist>", T("act.TotalCommander.TC_MoveDirectoryHotlist"))
    engine.SetAction("<TC_MoveSelectedFilesToPrevFolder>", T("act.TotalCommander.TC_MoveSelectedFilesToPrevFolder"))
    engine.SetAction("<TC_MoveUseQueues>", T("act.TotalCommander.TC_MoveUseQueues"))
    engine.SetAction("<TC_MultiFilePersistOpen>", T("act.TotalCommander.TC_MultiFilePersistOpen"))
    engine.SetAction("<TC_NormalMode>", T("act.TotalCommander.TC_NormalMode"))
    engine.SetAction("<TC_OpenDirAndPaste>", T("act.TotalCommander.TC_OpenDirAndPaste"))
    engine.SetAction("<TC_OpenDirsInFile>", T("act.TotalCommander.TC_OpenDirsInFile"))
    engine.SetAction("<TC_OpenDriveThat>", T("act.TotalCommander.TC_OpenDriveThat"))
    engine.SetAction("<TC_OpenDriveThis>", T("act.TotalCommander.TC_OpenDriveThis"))
    engine.SetAction("<TC_OpenWithAlternateViewer>", T("act.TotalCommander.TC_OpenWithAlternateViewer"))
    engine.SetAction("<TC_PasteFileEx>", T("act.TotalCommander.TC_PasteFileEx"))
    engine.SetAction("<TC_ReOpenTab>", T("act.TotalCommander.TC_ReOpenTab"))
    engine.SetAction("<TC_Restart>", T("act.TotalCommander.TC_Restart"))
    engine.SetAction("<TC_SearchMode>", T("act.TotalCommander.TC_SearchMode"))
    engine.SetAction("<TC_SelectCmd>", T("act.TotalCommander.TC_SelectCmd"))
    engine.SetAction("<TC_SrcQuickViewAndTab>", T("act.TotalCommander.TC_SrcQuickViewAndTab"))
    engine.SetAction("<TC_SuperReturn>", T("act.TotalCommander.TC_SuperReturn"))
    engine.SetAction("<TC_ThumbsView>", T("act.TotalCommander.TC_ThumbsView"))
    engine.SetAction("<TC_Toggle_50_100Percent_V>", T("act.TotalCommander.TC_Toggle_50_100Percent_V"))
    engine.SetAction("<TC_Toggle_50_100Percent>", T("act.TotalCommander.TC_Toggle_50_100Percent"))
    engine.SetAction("<TC_ToggleMenu>", T("act.TotalCommander.TC_ToggleMenu"))
    engine.SetAction("<TC_ToggleShowInfo>", T("act.TotalCommander.TC_ToggleShowInfo"))
    engine.SetAction("<TC_ToggleTC>", T("act.TotalCommander.TC_ToggleTC"))
    engine.SetAction("<TC_TwoFileExchangeName>", T("act.TotalCommander.TC_TwoFileExchangeName"))
    engine.SetAction("<TC_UnMarkFile>", T("act.TotalCommander.TC_UnMarkFile"))
    engine.SetAction("<TC_UpSelect>", T("act.TotalCommander.TC_UpSelect"))
    engine.SetAction("<TC_ViewFileUnderCursor>", T("act.TotalCommander.TC_ViewFileUnderCursor"))
    engine.SetAction("<TC_WinMaxLeft>", T("act.TotalCommander.TC_WinMaxLeft"))
    engine.SetAction("<TC_WinMaxRight>", T("act.TotalCommander.TC_WinMaxRight"))
    ; 注册窗口 (类名匹配, 不绑死进程名: 32 位 TOTALCMD.EXE / 64 位 TOTALCMD64.EXE 通吃)
    engine.SetWin("TTOTAL_CMD", "TTOTAL_CMD", "")
    engine.SetWin("TCQuickSearch", "TQUICKSEARCH", "")

    ; 注册模式
    engine.SetMode("normal", "TTOTAL_CMD")
    engine.SetMode("insert", "TTOTAL_CMD")
    engine.SetMode("search", "TTOTAL_CMD")
    engine.SetMode("normal", "TCQuickSearch")

    ; 设置 BeforeActionDo 回调 (仅 TTOTAL_CMD 窗, 对齐原版; 全局注册会误伤其它窗口)
    engine.SetBeforeActionDoForWin("TTOTAL_CMD", TC_BeforeActionDo)
    engine.SetPreKeyFilterForWin("TTOTAL_CMD", TC_PreKeyFilter)
    engine.RegisterPrefixActionHandler("cm_", TC_HandleCmAction)
    engine.RegisterActionValidator("cm_", TC_ValidateCmAction)
    engine.RegisterPrefixActionHandler("tccmd|", (action) => (TC_Run(SubStr(action, 7)), true))

    ; === 基础动作 ===
    engine.SetAction("<TC_NormalMode>", T("act.TotalCommander.TC_NormalMode"))
    engine.SetAction("<TC_InsertMode>", T("act.TotalCommander.TC_InsertMode"))
    engine.SetAction("<TC_ToggleTC>", T("act.TotalCommander.TC_ToggleTC"))
    engine.SetAction("<TC_Restart>", T("act.TotalCommander.TC_Restart_2"))

    ; === 导航 ===
    engine.SetAction("<TC_GoToParentEx>", T("act.TotalCommander.TC_GoToParentEx_2"))
    engine.SetAction("<cm_GotoRoot>", T("act.TotalCommander.cm_GotoRoot"))
    engine.SetAction("<cm_GotoPreviousDir>", T("act.TotalCommander.cm_GotoPreviousDir"))
    engine.SetAction("<cm_GotoNextDir>", T("act.TotalCommander.cm_GotoNextDir"))
    engine.SetAction("<TC_DownSelect>", T("act.TotalCommander.TC_DownSelect"))
    engine.SetAction("<TC_UpSelect>", T("act.TotalCommander.TC_UpSelect"))
    engine.SetAction("<TC_GotoLine>", T("act.TotalCommander.TC_GotoLine_2"))
    engine.SetAction("<TC_LastLine>", T("act.TotalCommander.TC_LastLine_2"))
    engine.SetAction("<TC_Half>", T("act.TotalCommander.TC_Half_2"))

    ; === 文件操作 ===
    engine.SetAction("<cm_CopyOtherpanel>", T("act.TotalCommander.cm_CopyOtherpanel_2"))
    engine.SetAction("<cm_MoveOnly>", T("act.TotalCommander.cm_MoveOnly_2"))
    engine.SetAction("<cm_CopyToClipboard>", T("act.TotalCommander.cm_CopyToClipboard_2"))
    engine.SetAction("<cm_CutToClipboard>", T("act.TotalCommander.cm_CutToClipboard_2"))
    engine.SetAction("<cm_PasteFromClipboard>", T("act.TotalCommander.cm_PasteFromClipboard_2"))
    engine.SetAction("<cm_Delete>", T("act.TotalCommander.cm_Delete"))
    engine.SetAction("<cm_RenameOnly>", T("act.TotalCommander.cm_RenameOnly_2"))
    engine.SetAction("<cm_MultiRenameFiles>", T("act.TotalCommander.cm_MultiRenameFiles"))
    engine.SetAction("<cm_MkDir>", T("act.TotalCommander.cm_MkDir"))
    engine.SetAction("<cm_Edit>", T("act.TotalCommander.cm_Edit_2"))
    engine.SetAction("<cm_View>", T("act.TotalCommander.cm_View"))
    engine.SetAction("<cm_PackFiles>", T("act.TotalCommander.cm_PackFiles"))
    engine.SetAction("<cm_UnpackFiles>", T("act.TotalCommander.cm_UnpackFiles"))
    engine.SetAction("<cm_CopyNamesToClip>", T("act.TotalCommander.cm_CopyNamesToClip"))
    engine.SetAction("<cm_CopyFullNamesToClip>", T("act.TotalCommander.cm_CopyFullNamesToClip_2"))
    engine.SetAction("<cm_CopySrcPathToClip>", T("act.TotalCommander.cm_CopySrcPathToClip_2"))
    engine.SetAction("<cm_CopyFileContents>", T("act.TotalCommander.cm_CopyFileContents"))

    ; === 搜索 ===
    engine.SetAction("<cm_SearchFor>", T("act.TotalCommander.cm_SearchFor_2"))
    engine.SetAction("<cm_ShowQuickSearch>", T("act.TotalCommander.cm_ShowQuickSearch_2"))

    ; === 比较 ===
    engine.SetAction("<cm_CompareDirs>", T("act.TotalCommander.cm_CompareDirs_2"))
    engine.SetAction("<cm_CompareByContent>", T("act.TotalCommander.cm_CompareByContent"))
    engine.SetAction("<cm_SyncDirs>", T("act.TotalCommander.cm_SyncDirs"))

    ; === 选择 ===
    engine.SetAction("<cm_SelectAll>", T("act.TotalCommander.cm_SelectAll_2"))
    engine.SetAction("<cm_ExchangeSelection>", T("act.TotalCommander.cm_ExchangeSelection_2"))
    engine.SetAction("<cm_ProperCase>", T("act.TotalCommander.cm_ProperCase"))
    engine.SetAction("<cm_LowerCase>", T("act.TotalCommander.cm_LowerCase"))
    engine.SetAction("<cm_UpperCase>", T("act.TotalCommander.cm_UpperCase"))

    ; === 刷新 ===
    engine.SetAction("<cm_Refresh>", T("act.TotalCommander.cm_Refresh"))

    ; === 标签页 ===
    engine.SetAction("<cm_OpenNewTab>", T("act.TotalCommander.cm_OpenNewTab"))
    engine.SetAction("<cm_OpenNewTabBg>", T("act.TotalCommander.cm_OpenNewTabBg_2"))
    engine.SetAction("<cm_SwitchToNextTab>", T("act.TotalCommander.cm_SwitchToNextTab_2"))
    engine.SetAction("<cm_SwitchToPreviousTab>", T("act.TotalCommander.cm_SwitchToPreviousTab_2"))
    engine.SetAction("<cm_CloseCurrentTab>", T("act.TotalCommander.cm_CloseCurrentTab"))
    engine.SetAction("<cm_CloseAllTabs>", T("act.TotalCommander.cm_CloseAllTabs"))
    engine.SetAction("<cm_SrcGoToLastTab>", T("act.TotalCommander.cm_SrcGoToLastTab"))

    ; === 排序 ===
    engine.SetAction("<cm_SrcByName>", T("act.TotalCommander.cm_SrcByName_2"))
    engine.SetAction("<cm_SrcByExt>", T("act.TotalCommander.cm_SrcByExt_2"))
    engine.SetAction("<cm_SrcBySize>", T("act.TotalCommander.cm_SrcBySize_2"))
    engine.SetAction("<cm_SrcByDateTime>", T("act.TotalCommander.cm_SrcByDateTime_2"))
    engine.SetAction("<cm_SrcByAttr>", T("act.TotalCommander.cm_SrcByAttr"))
    engine.SetAction("<cm_SrcNegSort>", T("act.TotalCommander.cm_SrcNegSort"))

    ; === 视图 ===
    engine.SetAction("<cm_SrcShort>", T("act.TotalCommander.cm_SrcShort_2"))
    engine.SetAction("<cm_SrcLong>", T("act.TotalCommander.cm_SrcLong_2"))
    engine.SetAction("<cm_SrcTree>", T("act.TotalCommander.cm_SrcTree_2"))
    engine.SetAction("<cm_SrcThumbs>", T("act.TotalCommander.cm_SrcThumbs_2"))
    engine.SetAction("<cm_SrcQuickView>", T("act.TotalCommander.cm_SrcQuickView"))
    engine.SetAction("<cm_ToggleTreeView>", T("act.TotalCommander.cm_ToggleTreeView"))

    ; === 窗口 ===
    engine.SetAction("<cm_MaximizePanel1>", T("act.TotalCommander.cm_MaximizePanel1"))
    engine.SetAction("<cm_MaximizePanel2>", T("act.TotalCommander.cm_MaximizePanel2"))
    engine.SetAction("<cm_Exchange>", T("act.TotalCommander.cm_Exchange_2"))
    engine.SetAction("<cm_Minimize>", T("act.TotalCommander.cm_Minimize_2"))
    engine.SetAction("<cm_Maximize>", T("act.TotalCommander.cm_Maximize_2"))
    engine.SetAction("<cm_Restore>", T("act.TotalCommander.cm_Restore_2"))

    ; === 其他 ===
    engine.SetAction("<cm_ContextMenu>", T("act.TotalCommander.cm_ContextMenu_2"))
    engine.SetAction("<cm_ExecuteDOS>", T("act.TotalCommander.cm_ExecuteDOS_2"))
    engine.SetAction("<cm_FocusCmdLine>", T("act.TotalCommander.cm_FocusCmdLine_2"))
    engine.SetAction("<cm_DirectoryHotlist>", T("act.TotalCommander.cm_DirectoryHotlist"))
    engine.SetAction("<cm_LeftOpenDrives>", T("act.TotalCommander.cm_LeftOpenDrives_2"))
    engine.SetAction("<cm_RightOpenDrives>", T("act.TotalCommander.cm_RightOpenDrives_2"))
    engine.SetAction("<cm_SrcHome>", T("act.TotalCommander.cm_SrcHome"))
    engine.SetAction("<cm_DirHome>", T("act.TotalCommander.cm_DirHome"))
    engine.SetAction("<cm_Config>", T("act.TotalCommander.cm_Config_2"))
    engine.SetAction("<cm_Exit>", T("act.TotalCommander.cm_Exit_2"))

    ; === 高级功能 ===
    engine.SetAction("<TC_Mark>", T("act.TotalCommander.TC_Mark"))
    engine.SetAction("<TC_ListMark>", T("act.TotalCommander.TC_ListMark"))
    engine.SetAction("<TC_azHistory>", T("act.TotalCommander.TC_azHistory"))
    engine.SetAction("<TC_CreateNewFile>", T("act.TotalCommander.TC_CreateNewFile_2"))
    engine.SetAction("<TC_ForceDelete>", T("act.TotalCommander.TC_ForceDelete"))
    engine.SetAction("<TC_Toggle_50_100Percent>", T("act.TotalCommander.TC_Toggle_50_100Percent_2"))
    engine.SetAction("<TC_AlwayOnTop>", T("act.TotalCommander.TC_AlwayOnTop_2"))
    engine.SetAction("<TC_ToggleShowInfo>", T("act.TotalCommander.TC_ToggleShowInfo_2"))
    engine.SetAction("<TC_SelectCmd>", T("act.TotalCommander.TC_SelectCmd_2"))
    engine.SetAction("<TC_OpenDriveThis>", T("act.TotalCommander.TC_OpenDriveThis_2"))
    engine.SetAction("<TC_OpenDriveThat>", T("act.TotalCommander.TC_OpenDriveThat_2"))
    engine.SetAction("<TC_ToggleMenu>", T("act.TotalCommander.TC_ToggleMenu_2"))
    engine.SetAction("<TC_ToggleToolbar>", T("act.TotalCommander.TC_ToggleToolbar"))
    engine.SetAction("<TC_ToggleStatusBar>", T("act.TotalCommander.TC_ToggleStatusBar"))
    engine.SetAction("<TC_WinMaxLeft>", T("act.TotalCommander.cm_MaximizePanel1"))
    engine.SetAction("<TC_WinMaxRight>", T("act.TotalCommander.cm_MaximizePanel2"))
    engine.SetAction("<TC_FileCopyForBak>", T("act.TotalCommander.TC_FileCopyForBak_2"))
    engine.SetAction("<TC_FileMoveForBak>", T("act.TotalCommander.TC_FileMoveForBak_2"))
    engine.SetAction("<TC_CreateFileShortcut>", T("act.TotalCommander.cm_CreateShortcut"))
    engine.SetAction("<TC_CreateFileShortcutToDesktop>", T("act.TotalCommander.TC_CreateFileShortcutToDesktop_2"))
    engine.SetAction("<TC_CreateBlankFile>", T("act.TotalCommander.TC_CreateBlankFile"))

    ; === 高级功能 ===
    engine.SetAction("<TC_CopyUseQueues>", T("act.TotalCommander.TC_CopyUseQueues_2"))
    engine.SetAction("<TC_MoveUseQueues>", T("act.TotalCommander.TC_MoveUseQueues_2"))
    engine.SetAction("<TC_CopyDirectoryHotlist>", T("act.TotalCommander.TC_CopyDirectoryHotlist"))
    engine.SetAction("<TC_MoveDirectoryHotlist>", T("act.TotalCommander.TC_MoveDirectoryHotlist"))
    engine.SetAction("<TC_GotoPreviousDirOther>", T("act.TotalCommander.TC_GotoPreviousDirOther_2"))
    engine.SetAction("<TC_GotoNextDirOther>", T("act.TotalCommander.TC_GotoNextDirOther_2"))
    engine.SetAction("<TC_SearchMode>", T("act.TotalCommander.TC_SearchMode_2"))
    engine.SetAction("<TC_ReOpenTab>", T("act.TotalCommander.TC_ReOpenTab_2"))
    engine.SetAction("<TC_GoLastTab>", T("act.TotalCommander.TC_GoLastTab_2"))
    engine.SetAction("<TC_Toggle_50_100Percent_V>", T("act.TotalCommander.TC_Toggle_50_100Percent_V_2"))
    engine.SetAction("<TC_SuperReturn>", T("act.TotalCommander.TC_SuperReturn_2"))
    engine.SetAction("<TC_MultiFilePersistOpen>", T("act.TotalCommander.TC_MultiFilePersistOpen_2"))
    engine.SetAction("<TC_CopyFileContents>", T("act.TotalCommander.cm_CopyFileContents"))
    engine.SetAction("<TC_OpenDirAndPaste>", T("act.TotalCommander.TC_OpenDirAndPaste_2"))
    engine.SetAction("<TC_MoveSelectedFilesToPrevFolder>", T("act.TotalCommander.TC_MoveSelectedFilesToPrevFolder_2"))
    engine.SetAction("<TC_MoveAllFilesToPrevFolder>", T("act.TotalCommander.TC_MoveAllFilesToPrevFolder_2"))
    engine.SetAction("<TC_SrcQuickViewAndTab>", T("act.TotalCommander.TC_SrcQuickViewAndTab_2"))
    engine.SetAction("<TC_CreateFileShortcutToStartup>", T("act.TotalCommander.TC_CreateFileShortcutToStartup_2"))
    engine.SetAction("<TC_FilterSearchFNsuffix_exe>", T("act.TotalCommander.TC_FilterSearchFNsuffix_exe_2"))
    engine.SetAction("<TC_TwoFileExchangeName>", T("act.TotalCommander.TC_TwoFileExchangeName_2"))
    engine.SetAction("<TC_MarkFile>", T("act.TotalCommander.TC_MarkFile_2"))
    engine.SetAction("<TC_UnMarkFile>", T("act.TotalCommander.TC_UnMarkFile_2"))
    engine.SetAction("<TC_ClearTitle>", T("act.TotalCommander.TC_ClearTitle_2"))
    engine.SetAction("<TC_OpenDirsInFile>", T("act.TotalCommander.TC_OpenDirsInFile_2"))
    engine.SetAction("<TC_CreateBlankFileNoExt>", T("act.TotalCommander.TC_CreateBlankFileNoExt_2"))
    engine.SetAction("<TC_PasteFileEx>", T("act.TotalCommander.TC_PasteFileEx_2"))
    engine.SetAction("<TC_ThumbsView>", T("act.TotalCommander.TC_ThumbsView_2"))
    engine.SetAction("<TC_SrcActivateTab1>", T("act.TotalCommander.TC_SrcActivateTab1"))
    engine.SetAction("<TC_SrcActivateTab2>", T("act.TotalCommander.TC_SrcActivateTab2"))
    engine.SetAction("<TC_SrcActivateTab3>", T("act.TotalCommander.TC_SrcActivateTab3"))
    engine.SetAction("<TC_SrcActivateTab4>", T("act.TotalCommander.TC_SrcActivateTab4"))
    engine.SetAction("<TC_SrcActivateTab5>", T("act.TotalCommander.TC_SrcActivateTab5"))
    engine.SetAction("<TC_SrcActivateTab6>", T("act.TotalCommander.TC_SrcActivateTab6"))
    engine.SetAction("<TC_SrcActivateTab7>", T("act.TotalCommander.TC_SrcActivateTab7"))
    engine.SetAction("<TC_SrcActivateTab8>", T("act.TotalCommander.TC_SrcActivateTab8"))
    engine.SetAction("<TC_SrcActivateTab9>", T("act.TotalCommander.TC_SrcActivateTab9"))

    ; === 映射热键 - normal 模式 (1:1 对原版 vim.map, 顺序同原版) ===

    ; 复制/移动 f=file (原版 fqc/fqx, 非移植版 fq/fQ)
    engine.MapKey("fc", "<cm_CopyOtherpanel>", "TTOTAL_CMD", "normal")
    engine.MapKey("fx", "<cm_MoveOnly>", "TTOTAL_CMD", "normal")
    engine.MapKey("fqc", "<TC_CopyUseQueues>", "TTOTAL_CMD", "normal")
    engine.MapKey("fqx", "<TC_MoveUseQueues>", "TTOTAL_CMD", "normal")
    engine.MapKey("ff", "<cm_CopyToClipboard>", "TTOTAL_CMD", "normal")
    engine.MapKey("fz", "<cm_CutToClipboard>", "TTOTAL_CMD", "normal")
    engine.MapKey("fv", "<cm_PasteFromClipboard>", "TTOTAL_CMD", "normal")
    engine.MapKey("fb", "<TC_CopyDirectoryHotlist>", "TTOTAL_CMD", "normal")
    engine.MapKey("fd", "<TC_MoveDirectoryHotlist>", "TTOTAL_CMD", "normal")
    engine.MapKey("fg", "<cm_CopySrcPathToClip>", "TTOTAL_CMD", "normal")
    engine.MapKey("ft", "<cm_SyncChangeDir>", "TTOTAL_CMD", "normal")
    engine.MapKey("F", "<TC_SearchMode>", "TTOTAL_CMD", "normal")
    engine.MapKey("gh", "<TC_GotoPreviousDirOther>", "TTOTAL_CMD", "normal")
    engine.MapKey("gl", "<TC_GotoNextDirOther>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vh", "<cm_SwitchIgnoreList>", "TTOTAL_CMD", "normal")

    ; 数字键 (原版 <TC_0-9> 只清 count 不打字; v2 空函数复刻, 不用 <Pass> 透传)
    engine.MapKey("0", "<TC_0>", "TTOTAL_CMD", "normal")
    engine.MapKey("1", "<TC_1>", "TTOTAL_CMD", "normal")
    engine.MapKey("2", "<TC_2>", "TTOTAL_CMD", "normal")
    engine.MapKey("3", "<TC_3>", "TTOTAL_CMD", "normal")
    engine.MapKey("4", "<TC_4>", "TTOTAL_CMD", "normal")
    engine.MapKey("5", "<TC_5>", "TTOTAL_CMD", "normal")
    engine.MapKey("6", "<TC_6>", "TTOTAL_CMD", "normal")
    engine.MapKey("7", "<TC_7>", "TTOTAL_CMD", "normal")
    engine.MapKey("8", "<TC_8>", "TTOTAL_CMD", "normal")
    engine.MapKey("9", "<TC_9>", "TTOTAL_CMD", "normal")

    ; 基础导航 (与原版一致)
    engine.MapKey("j", "<down>", "TTOTAL_CMD", "normal")
    engine.MapKey("k", "<up>", "TTOTAL_CMD", "normal")
    engine.MapKey("h", "<left>", "TTOTAL_CMD", "normal")
    engine.MapKey("l", "<right>", "TTOTAL_CMD", "normal")
    engine.MapKey("J", "<TC_DownSelect>", "TTOTAL_CMD", "normal")
    engine.MapKey("K", "<TC_UpSelect>", "TTOTAL_CMD", "normal")
    engine.MapKey("M", "<TC_Half>", "TTOTAL_CMD", "normal")
    engine.MapKey("gg", "<TC_GoToLine>", "TTOTAL_CMD", "normal")
    engine.MapKey("G", "<TC_LastLine>", "TTOTAL_CMD", "normal")
    engine.MapKey("H", "<cm_GotoPreviousDir>", "TTOTAL_CMD", "normal")
    engine.MapKey("L", "<cm_GotoNextDir>", "TTOTAL_CMD", "normal")
    engine.MapKey("u", "<TC_GoToParentEx>", "TTOTAL_CMD", "normal")
    engine.MapKey("U", "<cm_GotoRoot>", "TTOTAL_CMD", "normal")
    engine.MapKey("<Esc>", "<TC_NormalMode>", "TTOTAL_CMD", "insert")

    ; 文件操作 (与原版一致; w=cm_List 非 cm_View; I/i 不动)
    engine.MapKey("x", "<cm_Delete>", "TTOTAL_CMD", "normal")
    engine.MapKey("X", "<TC_ForceDelete>", "TTOTAL_CMD", "normal")
    engine.MapKey("r", "<cm_RenameOnly>", "TTOTAL_CMD", "normal")
    engine.MapKey("R", "<cm_MultiRenameFiles>", "TTOTAL_CMD", "normal")
    engine.MapKey("n", "<TC_azHistory>", "TTOTAL_CMD", "normal")
    engine.MapKey("I", "<TC_CreateNewFile>", "TTOTAL_CMD", "normal")
    engine.MapKey("e", "<cm_ContextMenu>", "TTOTAL_CMD", "normal")
    engine.MapKey("E", "<cm_ExecuteDOS>", "TTOTAL_CMD", "normal")
    engine.MapKey("i", "<TC_InsertMode>", "TTOTAL_CMD", "normal")
    engine.MapKey(":", "<cm_FocusCmdLine>", "TTOTAL_CMD", "normal")

    ; 复制/移动 (上部 f 系列已对原版; fa 归 ini, fp/fq 系移植版自创已 drop, 后续按需加回)

    ; 查看/搜索 (w=cm_List 对原版, 非 cm_View)
    engine.MapKey("w", "<cm_List>", "TTOTAL_CMD", "normal")
    engine.MapKey("q", "<cm_SrcQuickView>", "TTOTAL_CMD", "normal")
    engine.MapKey("/", "<cm_ShowQuickSearch>", "TTOTAL_CMD", "normal")
    engine.MapKey("?", "<cm_SearchFor>", "TTOTAL_CMD", "normal")

    ; 复制信息
    engine.MapKey("y", "<cm_CopyNamesToClip>", "TTOTAL_CMD", "normal")
    engine.MapKey("Y", "<cm_CopyFullNamesToClip>", "TTOTAL_CMD", "normal")

    ; 压缩/解压
    engine.MapKey("P", "<cm_PackFiles>", "TTOTAL_CMD", "normal")
    engine.MapKey("p", "<cm_UnpackFiles>", "TTOTAL_CMD", "normal")

    ; 选择 (原版全量: [ ] { } \ | ; a 走 ini)
    engine.MapKey("[", "<cm_SelectCurrentName>", "TTOTAL_CMD", "normal")
    engine.MapKey("{", "<cm_UnselectCurrentName>", "TTOTAL_CMD", "normal")
    engine.MapKey("]", "<cm_SelectCurrentExtension>", "TTOTAL_CMD", "normal")
    engine.MapKey("}", "<cm_UnSelectCurrentExtension>", "TTOTAL_CMD", "normal")
    engine.MapKey("\", "<cm_ExchangeSelection>", "TTOTAL_CMD", "normal")
    engine.MapKey("|", "<cm_ClearAll>", "TTOTAL_CMD", "normal")

    ; 符号键 (原版: -/=/~/` ; . 归 ini/custom, 不在硬编码)
    engine.MapKey("-", "<cm_SwitchSeparateTree>", "TTOTAL_CMD", "normal")
    engine.MapKey("=", "<cm_MatchSrc>", "TTOTAL_CMD", "normal")
    engine.MapKey("~", "<cm_SysInfo>", "TTOTAL_CMD", "normal")
    engine.MapKey("``", "<TC_ToggleShowInfo>", "TTOTAL_CMD", "normal")
    engine.MapKey(",", "<cm_SrcThumbs>", "TTOTAL_CMD", "normal")
    engine.MapKey(";", "<cm_DirectoryHotlist>", "TTOTAL_CMD", "normal")

    ; 驱动器 (与原版一致)
    engine.MapKey("o", "<cm_LeftOpenDrives>", "TTOTAL_CMD", "normal")
    engine.MapKey("O", "<cm_RightOpenDrives>", "TTOTAL_CMD", "normal")
    engine.MapKey("d", "<cm_DirectoryHotlist>", "TTOTAL_CMD", "normal")
    engine.MapKey("D", "<cm_OpenDesktop>", "TTOTAL_CMD", "normal")

    ; 标签页 (原版: g1-9=cm_SrcActivateTab, g0=TC_GoLastTab, 无 Gen_Tab*)
    engine.MapKey("t", "<cm_OpenNewTab>", "TTOTAL_CMD", "normal")
    engine.MapKey("T", "<cm_OpenNewTabBg>", "TTOTAL_CMD", "normal")
    engine.MapKey("g0", "<TC_GoLastTab>", "TTOTAL_CMD", "normal")
    engine.MapKey("g1", "<cm_SrcActivateTab1>", "TTOTAL_CMD", "normal")
    engine.MapKey("g2", "<cm_SrcActivateTab2>", "TTOTAL_CMD", "normal")
    engine.MapKey("g3", "<cm_SrcActivateTab3>", "TTOTAL_CMD", "normal")
    engine.MapKey("g4", "<cm_SrcActivateTab4>", "TTOTAL_CMD", "normal")
    engine.MapKey("g5", "<cm_SrcActivateTab5>", "TTOTAL_CMD", "normal")
    engine.MapKey("g6", "<cm_SrcActivateTab6>", "TTOTAL_CMD", "normal")
    engine.MapKey("g7", "<cm_SrcActivateTab7>", "TTOTAL_CMD", "normal")
    engine.MapKey("g8", "<cm_SrcActivateTab8>", "TTOTAL_CMD", "normal")
    engine.MapKey("g9", "<cm_SrcActivateTab9>", "TTOTAL_CMD", "normal")

    ; 标签页管理 (原版: gb=对侧新标签, gw=带标签交换, gr=重开)
    engine.MapKey("ga", "<cm_CloseAllTabs>", "TTOTAL_CMD", "normal")
    engine.MapKey("gc", "<cm_CloseCurrentTab>", "TTOTAL_CMD", "normal")
    engine.MapKey("gt", "<cm_SwitchToNextTab>", "TTOTAL_CMD", "normal")
    engine.MapKey("gT", "<cm_SwitchToPreviousTab>", "TTOTAL_CMD", "normal")
    engine.MapKey("ge", "<cm_Exchange>", "TTOTAL_CMD", "normal")
    engine.MapKey("gb", "<cm_OpenDirInNewTabOther>", "TTOTAL_CMD", "normal")
    engine.MapKey("gr", "<TC_ReOpenTab>", "TTOTAL_CMD", "normal")
    engine.MapKey("gw", "<cm_ExchangeWithTabs>", "TTOTAL_CMD", "normal")
    engine.MapKey("g$", "<TC_LastLine>", "TTOTAL_CMD", "normal")

    ; 排序 (原版: sr=NegOrder, s1-9=按列, s0=无序)
    engine.MapKey("sn", "<cm_SrcByName>", "TTOTAL_CMD", "normal")
    engine.MapKey("se", "<cm_SrcByExt>", "TTOTAL_CMD", "normal")
    engine.MapKey("ss", "<cm_SrcBySize>", "TTOTAL_CMD", "normal")
    engine.MapKey("sd", "<cm_SrcByDateTime>", "TTOTAL_CMD", "normal")
    engine.MapKey("sr", "<cm_SrcNegOrder>", "TTOTAL_CMD", "normal")
    engine.MapKey("s1", "<cm_SrcSortByCol1>", "TTOTAL_CMD", "normal")
    engine.MapKey("s2", "<cm_SrcSortByCol2>", "TTOTAL_CMD", "normal")
    engine.MapKey("s3", "<cm_SrcSortByCol3>", "TTOTAL_CMD", "normal")
    engine.MapKey("s4", "<cm_SrcSortByCol4>", "TTOTAL_CMD", "normal")
    engine.MapKey("s5", "<cm_SrcSortByCol5>", "TTOTAL_CMD", "normal")
    engine.MapKey("s6", "<cm_SrcSortByCol6>", "TTOTAL_CMD", "normal")
    engine.MapKey("s7", "<cm_SrcSortByCol7>", "TTOTAL_CMD", "normal")
    engine.MapKey("s8", "<cm_SrcSortByCol8>", "TTOTAL_CMD", "normal")
    engine.MapKey("s9", "<cm_SrcSortByCol9>", "TTOTAL_CMD", "normal")
    engine.MapKey("s0", "<cm_SrcUnsorted>", "TTOTAL_CMD", "normal")

    ; 视图 (原版 V 系=界面显隐开关, 非移植版重构版)
    engine.MapKey("v", "<cm_SrcCustomViewMenu>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vb", "<cm_VisButtonbar>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vm", "<TC_ToggleMenu>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vd", "<cm_VisDriveButtons>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vo", "<cm_VisTwoDriveButtons>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vr", "<cm_VisDriveCombo>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vc", "<cm_VisDriveCombo>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vt", "<cm_VisTabHeader>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vs", "<cm_VisStatusbar>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vn", "<cm_VisCmdLine>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vf", "<cm_VisKeyButtons>", "TTOTAL_CMD", "normal")
    engine.MapKey("Vw", "<cm_VisDirTabs>", "TTOTAL_CMD", "normal")
    engine.MapKey("Ve", "<cm_CommandBrowser>", "TTOTAL_CMD", "normal")

    ; 窗口 (原版: zz/zh=50/100切换, zi/zo=左右最大化, zn/zm/zr=最小/大/还原, zv=纵向)
    engine.MapKey("zz", "<TC_Toggle_50_100Percent>", "TTOTAL_CMD", "normal")
    engine.MapKey("zh", "<TC_Toggle_50_100Percent_V>", "TTOTAL_CMD", "normal")
    engine.MapKey("zi", "<TC_WinMaxLeft>", "TTOTAL_CMD", "normal")
    engine.MapKey("zo", "<TC_WinMaxRight>", "TTOTAL_CMD", "normal")
    engine.MapKey("zt", "<TC_AlwayOnTop>", "TTOTAL_CMD", "normal")
    engine.MapKey("zn", "<cm_Minimize>", "TTOTAL_CMD", "normal")
    engine.MapKey("zm", "<cm_Maximize>", "TTOTAL_CMD", "normal")
    engine.MapKey("zr", "<cm_Restore>", "TTOTAL_CMD", "normal")
    engine.MapKey("zv", "<cm_VerticalPanels>", "TTOTAL_CMD", "normal")

    ; 高级 (与原版一致)
    engine.MapKey("m", "<TC_Mark>", "TTOTAL_CMD", "normal")
    engine.MapKey("'", "<TC_ListMark>", "TTOTAL_CMD", "normal")
    engine.MapKey("``", "<TC_ToggleShowInfo>", "TTOTAL_CMD", "normal")
    engine.MapKey("-", "<TC_Toggle_50_100Percent>", "TTOTAL_CMD", "normal")
    engine.MapKey(";", "<cm_DirectoryHotlist>", "TTOTAL_CMD", "normal")

    ; (原版硬编码到此结束; 以下移植版自创键已移除, 回归原版:
    ;  F10/fB/fM/fs/fS/fi/fI/fq/fQ/fD/fa/ft/fe/fw/fm/fu/gv/gU/gA/gI/z;/Enter/go/gO,
    ;  其中 fa 归 ini 所有, F/gt 与上部重复不再列出)

    ; insert 模式映射
    engine.MapKey("<enter>", "<enter>", "TTOTAL_CMD", "insert")
    engine.MapKey("<bs>", "<bs>", "TTOTAL_CMD", "insert")
    engine.MapKey("<tab>", "<tab>", "TTOTAL_CMD", "insert")
    engine.MapKey("<space>", "<space>", "TTOTAL_CMD", "insert")
    engine.MapKey("<del>", "<del>", "TTOTAL_CMD", "insert")

    ; 快速搜索窗口
    engine.MapKey("j", "<down>", "TCQuickSearch", "normal")
    engine.MapKey("k", "<up>", "TCQuickSearch", "normal")

    ; 菜单字母直达键启动时一次注册常驻 (HotIf 限定 TCMenu 作用域, 平时休眠):
    ; 原先每弹一次绑 36 个热键, 钩子抖动窗口内 arriving 的快速第二键可能丢失,
    ; 且弹出路径变长. 弹/关不再绑/解 (TC_MenuBindKeys/UnbindKeys 保留备用)
    TC_MenuBindKeys()

    ; 注册上下文提供者
    try {
        RimContext.RegisterProvider("totalcommander", TC_ContextProvider)
    }
}
