; VimRunZ 默认皮肤
; 对齐 RunZ Conf\Skins\Default.ini

[Gui]
HideTitle=1
ShowTrayIcon=1
ShowCurrentCommand=1
DisplayRows=15
DisplayCol3MaxLength=25
DisplayCol4MaxLength=35
HideCol2=0
HideCol4IfEmpty=1
FontName=宋体
FontSize=12
FontColor=000000
WidgetWidth=600
EditHeight=24
DisplayAreaHeight=246
FirstChar=a
EditColor=f0f0f0
BackgroundColor=f0f0f0
BackgroundPicture=Background.jpg
BorderSize=15
ShowInputBoxOnlyIfEmpty=0
RoundCorner=0
